# dq_checks/schemas.py

BIGDATA_COLUMNS = {
    "District": "string",
    "Control Section Job": "string",
    "Controlling Project ID": "string",
    "Fiscal Year": "number",
    "ESTIMATED LET DATE": "datetime",
    "COUNTY": "string",
    "HIGHWAY": "string",
    "PROJECT CLASS": "string",
    "PROJECT DESCRIPTION": "string",
    "LIMITS FROM": "string",
    "LIMITS TO": "string",
    "MPO Name": "string",
    "CONSTRUCTION ESTIMATE": "number",
    "UTP Action": "string",
    "FUNDING LINE ORDER #": "number",
    "CATEGORY": "string",
    "WORK PROGRAM": "string",
    "AUTHORIZED AMOUNT": "number",
    "FIXED FUNDS": "string",
    "PID": "string",
    "FUNDING APPROVAL STATUS": "string",
    "TOLL FLAG": "string",
    "Cat 2 Total Recommened": "number",
    "Cat 4U Total Recommened": "number",
    "Cat 4R Total Recommended": "number",
    "Cat 12TTC Total Recommended": "number",
    "Cat 12CL Total Recommened": "number",
    "FUNDING GROUP NAME": "string",
    "ACTUAL LET DATE": "string",
    "LETTING ESTIMATE": "number"
}